### ISSUE TITLE
Cannot load anime list

### ISSUE THREAD

**Issue by YazanMehyar** [HIGHWAY99/plugin.video.kissanime#12]
Hello Highway99,

I've been using the kissanime plugin recently and it worked just fine (anime list loading, video playing). One (dreaded) day when I requested to view the available list of anime via various means such as text searching or narrowing it down by genre or by selecting 'Anime List [Alphabet]' for example, I get a pop-up message with contents:

> Results: movies
> no results were found

The version I have installed on kodi is 0.9.19.

Looking back on previous issues it looks awfully similar to issue #5 
Is this a cloud flare issue (or sth similar)?

**Comment by Sindbadboys** [comment]
I am havIng the same prOblem.  Can sOmeOne please help!

**Comment by YazanMehyar** [comment]
Hi Sinbadboys,
The issue with mine was not the code but with kissanime's security.
Kissanime attempts to block programs that scrape for videos without showing ads.
I accessed the site from my laptop using a browser. My laptop was hooked to the same network 
which whatever device Kodi was on. Once I did, somehow the it fixed itself.
If that doesn't work, it might be a spontaneous error.

**Comment by Sindbadboys** [comment]
Thanks a lot, it fixed it self.  I had this problem for probably 2 months
now trying to find a solution and here I am.  Thanks again!
