### ISSUE TITLE
KissAnime.com DDOS Protection Breaks Plugin

### ISSUE THREAD

**Issue by coryjamesfisher** [HIGHWAY99/plugin.video.kissanime#2]
Hello Highway99,

Thank you for all of your hard work on this plugin.
I noticed yesterday in the log that the DDOS Protection is breaking the plugin as
they use a javascript redirect which curl can not follow.

I know there are ways around this but I also know that they are very complicated and probably impossible considering the amount of devices Kodi/XBMC are running on.

Do you have any kind of relationship with the KissAnime.com maintainers? 
Is there any way they could provide a simple webservice request to allow the plugin
to bypass the DDOS protection?
I would envision the flow would be something like this:
1) Resource requested (as it is today in your plugin)
2) Invalid response passed back.
3) Send webservice request to kissanime which returns a captcha image
4) Prompt user for input
5) Send webservice request to verify captcha against input
6) Return cookie allowing bypass of ddos for N hours

I would be happy to help implement this if you have a line of communication with them.
Regards,
Cory

**Comment by HIGHWAY99** [comment]
The addon ain't exactly a huge selling point as it is, so i'd rather not push my luck a lot.  Javascript isn't very possible in some installs of xbmc, yes.  However, most javascript, so long as it doesn't change out of the blue, can be coded for so long as it doesn't get too complex.  The latest version's CF Protection work-a-round should be working now.
