### ISSUE TITLE
ISSUE WITH  UPDATE 0.9.2 

### ISSUE THREAD

**Issue by ISSUES100** [HIGHWAY99/plugin.video.kissanime#3]
HI HIGHWAY99
A FEW HOURS AGO I INSTALLED UPDATE 0.9.2 and now i cant see the related series of all anime excempt of their dub version what happened?(example ghost in the shell).
also once in a while the mark next to my watched episodes dissapears for some it comes back for others it does not , why is that?
kenzen robo daimidaler always had the problem with related series.
there was an anime that i had passed in the favorites but after reinstalling kiss anime addon i couldnt find it anymore i remembere it starting from the letter b (i could have found since it sits faintly in my mind)it was only in dub i even remember more or less its image but its nowhere to be found..i havent check the webpage yet but it should have been in the addon...!

**Comment by HIGHWAY99** [comment]
Thank you, I'll get it fixed for the next version, and see about making sure that it gets pushed for K.C. as well as K.A.
