### ISSUE TITLE
testing html_last is empty?

### ISSUE THREAD

**Issue by persian12** [HIGHWAY99/plugin.video.kissanime#5]
hello

im using minix x7 with quickshot 3.0 with kodi 14.2 helix, im using kissanime  0.92  update, im geting an error.

testing 
html_last is empty.

![20150327_201946](https://cloud.githubusercontent.com/assets/11688145/6879007/d6b05968-d4bf-11e4-8b89-6f47e40dd324.jpg)

thanks i love the kissanime.

**Comment by ISSUES100** [comment]
u mean the last anime visited right?
for me it produced one error once today , after watching a new anime episode from "the latest update" page when i exited that menu and entered the "last anime visited" it opened instead the previeus menu i was in (the latest update) and when i exited this in the place of yesterdays "last anime visited"  was the name of the new anime episode i watched before.
but that error only happened once.!

**Comment by persian12** [comment]
the latest  update is not loading but if i add something to my bookmarks from the web actually works i install the kodi helix 14.2 and now when i hit latest update it will search infinite and will not load, i will re install the kodi 14.0 and  try.

**Comment by persian12** [comment]
ok i did a clean installation of kodi helix  and install the kiss anime repo is working fine.

**Comment by HIGHWAY99** [comment]
v.0.9.2 wasn't able to get past the CF protection that was blocking stuff on the site.  Try v0.9.6 until v0.9.7 gets released.
