### ISSUE TITLE
cloudfare is up again in the website.

### ISSUE THREAD

**Issue by ISSUES100** [HIGHWAY99/plugin.video.kissanime#6]
is the anti cf ddos protection code in the plugin? 
and if yes which setting is it in order to enable it .!

**Comment by HIGHWAY99** [comment]
It's enabled automatically, nothing to enable/disable on it atm.  When doing working-a-round(s) for protection methods... methods tend to get changed.  Can't expect to have it always working 100% when even their own apps aren't, LoL.  But, stuff should be playable atm.  DL feature fix in v0.9.7, though jDownloader method will probably still have an issue.
