### ISSUE TITLE
Cloudflare protection Issue

### ISSUE THREAD

**Issue by Trancesmaster** [HIGHWAY99/plugin.video.kissanime#7]
Can you please fix it thank, if not could create an addon from these websites, all of them provide HD streaming like Kissanime

http://animejoy.tv

http://www.animejolt.tv

http://www.anime4fun.com

**Comment by HIGHWAY99** [comment]
People gotta seriously have some patients.  And go easy on a site when it's behind CloudFlare Protection, so it's not getting heavy usage while being attacked or dealing with fixing things on their end.

PS:  I don't forsee dropping this addon anytime soon, and I already got tons of other addons for anime.  So, I'm not looking to do any for additional sites at this time.  Though, those wanting to join me in #The_Projects on irc chat, could potentially learn how to make one for them, might have a new addon template coming out sometime soon-ish.
