### ISSUE TITLE
problem with methods in the settings

### ISSUE THREAD

**Issue by ISSUES100** [HIGHWAY99/plugin.video.kissanime#9]
the 6th link started seemingly in 1st half of 2015 appears as number 5 link

question1 : is it possible to add numbers in front of the related series to show which one comes first? 
(for remake of movies the same number can be added)

question2: is it possible to add info in the animes page whether its an c.g.i or not? (maybe also 2d/3d).

thanks for this great addon-i use daily.!!!

**Comment by HIGHWAY99** [comment]
I'll have 6th link text fixed in settings for v0.9.7.

A1:  I dont forsee any knowledge base to at hand to grab such information from for what is / isn't a remake and such.

A2:  Again, there's no where to on-hand in the pages to grab such information.  I want as few page pulls as possible.
